import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://cms-staging.qbookapp.com/login")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("muhmmdfdln@gmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Qbook@2025")
    page.get_by_role("textbox", name="Password").press("Enter")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("complementary").locator("div").filter(has_text="Main AppDashboardRESERVATIONFloor PlanReservation ListScheduleTime").get_by_role("button").click()
    page.get_by_role("link", name="Floor Plan").click()
    page.get_by_text("BAKU, SCBD").click()
    page.get_by_text("KN Testing").click()
    page.locator("div").filter(has_text=re.compile(r"^B6$")).first.click()
    page.get_by_role("button", name="edit Reservation").click()
    page.get_by_text("Adult (4)").click()
    page.get_by_role("button", name="plus").first.click()
    page.get_by_label("Add Guests").get_by_role("button", name="Save").click()
    page.get_by_text("14:30", exact=True).click()
    page.get_by_role("button", name="3 PM").click()
    page.get_by_role("button", name="30").click()
    page.get_by_text("1hr (Default)").click()
    page.get_by_text("1hr 15min").click()
    page.get_by_label("Select Start Time").get_by_role("button", name="Save").click()
    page.locator("div").filter(has_text=re.compile(r"^Customer$")).nth(2).click()
    page.get_by_role("textbox", name="Search customer by name,").click()
    page.get_by_role("textbox", name="Search customer by name,").fill("881012177133")
    page.get_by_text("Fadlan Test+62881012177133A5").click()
    page.get_by_role("button", name="Save and Add to Reservation").click()
    page.get_by_role("textbox", name="Input party name").click()
    page.get_by_role("textbox", name="Input party name").fill("ITC++")
    page.locator("div").filter(has_text=re.compile(r"^Preferences$")).nth(1).click()
    page.get_by_role("button", name="down Smoking Preferences").click()
    page.get_by_text("PreviewSmoking").click()
    page.get_by_role("button", name="up Smoking Preferences").click()
    page.get_by_role("button", name="Save 14 Preferences").click()
    page.locator("div").filter(has_text=re.compile(r"^Menu Packages$")).nth(1).click()
    page.locator(".ant-checkbox-input").first.check()
    page.get_by_role("button", name="OK").click()
    page.locator(".ant-select.ant-select-outlined.ant-select-in-form-item.css-1nf76zr.ant-select-single.ant-select-allow-clear > .ant-select-selector").first.click()
    page.get_by_title("Mall", exact=True).click()
    page.get_by_text("Direct").click()
    page.get_by_title("Ismaya+").locator("div").click()
    page.locator("div:nth-child(22) > .ant-row > .ant-col > .ant-form-item-control-input > .ant-form-item-control-input-content > div").click()
    page.locator("div").filter(has_text=re.compile(r"^TESTT$")).nth(3).click()
    page.locator("div").filter(has_text=re.compile(r"^TESTTT$")).nth(1).click()
    page.get_by_label("Choose Reservation Flag").get_by_role("button", name="Save").click()
    page.get_by_text("ACCEPTED").click()
    page.get_by_text("CONFIRMED").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="FadlanKuy").click()
    page.get_by_text("FAFadlan QASuper Admin (3)").click()
    page.get_by_role("menuitem", name="logout Logout").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
