import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://cms-staging.qbookapp.com/login")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("muhmmdfdln@gmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Qbook@2026")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("complementary").locator("div").filter(has_text="DashboardRESERVATIONFloor").get_by_role("button").click()
    page.get_by_role("link", name="Master Data").click()
    page.get_by_role("img", name="shop", exact=True).locator("svg").click()
    page.locator(".ant-select-selector").first.click()
    page.locator(".ant-select-selector").first.click()
    page.get_by_role("option", name="KN Testing").click()
    page.get_by_role("button", name="plus Add Purpose").click()
    page.get_by_role("textbox", name="Purpose Name").click()
    page.get_by_role("textbox", name="Purpose Name").fill("AutoTest01")
    page.get_by_role("button", name="Create").click()
    page.locator(".ant-input-affix-wrapper").first.click()
    page.get_by_role("textbox", name="Search").first.fill("Auto")
    page.get_by_role("row", name="AutoTest01 16 Jul 2026 15:51").get_by_role("cell").nth(3).click()
    page.get_by_role("row", name="AutoTest01 16 Jul 2026 15:51").locator("svg").click()
    page.get_by_role("menuitem", name="Delete", exact=True).click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("textbox", name="Search").first.click()
    page.get_by_role("textbox", name="Search").first.fill("")
    page.get_by_role("button", name="plus Add Channel").click()
    page.get_by_role("textbox", name="Channel Name").click()
    page.get_by_role("textbox", name="Channel Name").fill("AutoTest")
    page.get_by_role("button", name="Create").click()
    page.get_by_role("row", name="AutoTest 16 Jul 2026 15:52 16").locator("svg").click()
    page.get_by_role("menuitem", name="Delete", exact=True).click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="plus Add Source").click()
    page.get_by_role("textbox", name="Source Name").click()
    page.get_by_role("textbox", name="Source Name").click()
    page.get_by_role("textbox", name="Source Name").fill("Protest")
    page.get_by_role("button", name="Create").click()
    page.get_by_role("row", name="Protest 16 Jul 2026 15:53 16").locator("svg").click()
    page.get_by_role("menuitem", name="Delete", exact=True).click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="plus Add Flag").click()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill("AutoTest")
    page.locator("label").filter(has_text="Yellow").locator("span").nth(1).click()
    page.get_by_role("radio", name="Yellow").check()
    page.locator("#iconName > div:nth-child(9) > div").click()
    page.locator("#iconName > div:nth-child(10) > div").click()
    page.get_by_role("button", name="Create").click()
    page.get_by_role("row", name="1 AutoTest 16 Jul 2026 15:54").locator("svg").nth(1).click()
    page.get_by_role("menuitem", name="Delete", exact=True).click()
    page.get_by_role("button", name="OK").click()
    page.get_by_text("FAFadlan QASuper Admin").click()
    page.get_by_role("menuitem", name="logout Logout").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
